on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
    - uses: actions/checkout@v7
    - uses: reviewdog/action-shellcheck@d0b8d5fd7fad6afdb6e1b6ce1778892be4d1f427 # v1.34.1
      with:
        reporter: github-check
        level: warning
        pattern: "svm"
