on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
    - uses: actions/checkout@v7
    - uses: reviewdog/action-shellcheck@0a90156c6e0553996a217f0a9e09be6b0f6bee4c # v1.34.0
      with:
        reporter: github-check
        level: warning
        pattern: "svm"
